title: "Career Mentoring and Professional Identity Development"
subtitle: "CS 386-01 &bullet; Fall 2021"

campuswire: "https://campuswire.com/c/G4C9C10A6"
canvas: "https://usfca.instructure.com/courses/1603246"
github: "https://github.com/usf-cs386-fall2021"
zoom: "https://usfca.zoom.us/j/87482848820"

coordinates: Classes will be held in HR 435 from **4:45&ndash;6:25pm**.

description: >-
  This course gives students the opportunity to engage with alumni mentors from industry and develop their identities as computing professionals.

  Computer science is a broad, diverse field. No matter your background, your hobbies, or your working style, computer science has a place for you. Finding that place and navigating the field may seem daunting at times, but we aim to build a support structure through classmates, peers, teachers, and mentors to make the journey easier.


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
